// data-processing-action-type.labels.ts
import { DataProcessingActionType } from './data-processing-action-type.enum';

export const DataProcessingActionTypeLabels: Record<DataProcessingActionType, string> = {
  [DataProcessingActionType.ACCESS]: 'Controls access to data or use of data.',
  [DataProcessingActionType.AGGREGATION]: 'Aggregates multiple datasets to produce summaries or combined statistics.',
  [DataProcessingActionType.ANALYSIS]: 'Analyses data for patterns, insights, or profiling.',
  [DataProcessingActionType.ANONYMISATION]: 'Removes identifiers from data irreversibly.',
  [DataProcessingActionType.ARCHIVING]: 'Archives data for long-term retention.',
  [DataProcessingActionType.AUDIT]: 'Reviews how data was processed, including examining logs or audit trails.',
  [DataProcessingActionType.BACKUP]: 'Creates backups of data for disaster recovery or redundancy.',
  [DataProcessingActionType.CLEANSING]: 'Removes irrelevant, outdated, incorrect, or duplicate data.',
  [DataProcessingActionType.COLLECTION]: 'Collects personal or sensitive data from individuals or systems.',
  [DataProcessingActionType.COMPOSITION]: 'Combines or assembles data elements into new datasets.',
  [DataProcessingActionType.CONVERSION]: 'Converts data from one format or standard to another.',
  [DataProcessingActionType.CRAWLING]: 'Scrapes data from websites or other digital sources.',
  [DataProcessingActionType.CREATION]: 'Creates new data records or datasets.',
  [DataProcessingActionType.CURATION]: 'Selects, organises, and maintains data for accuracy and usefulness.',
  [DataProcessingActionType.DEDUPLICATION]: 'Identifies and removes duplicate records from datasets.',
  [DataProcessingActionType.DECRYPTION]: 'Decrypts data to make it readable again.',
  [DataProcessingActionType.DELETION]: 'Deletes data manually or programmatically.',
  [DataProcessingActionType.DESTRUCTION]: 'Destroys data irreversibly, often for compliance purposes.',
  [DataProcessingActionType.DISPOSAL]: 'Disposes of physical or digital data assets securely.',
  [DataProcessingActionType.DISTRIBUTION]: 'Distributes or delivers data to intended recipients.',
  [DataProcessingActionType.EDITING]: 'Modifies or updates data content.',
  [DataProcessingActionType.ENCRYPTION]: 'Encrypts data using cryptographic methods.',
  [DataProcessingActionType.ENRICHMENT]: 'Enhances data by adding new or supplementary information.',
  [DataProcessingActionType.EXPORT]: 'Sends or delivers data to an external system, location, or organisation.',
  [DataProcessingActionType.EXTRACTION]: 'Retrieves data from one or more source systems (e.g., databases, APIs, files).',
  [DataProcessingActionType.FILTERING]: 'Selects or excludes subsets of data based on defined conditions or rules.',
  [DataProcessingActionType.IMPORT]: 'Brings or loads data from an external system, location, or organisation.',
  [DataProcessingActionType.INGESTION]: 'Acquires and imports data into a system or platform.',
  [DataProcessingActionType.INSPECTION]: 'Examines data to identify content, structure, or issues.',
  [DataProcessingActionType.LINKING]: 'Associates related data from multiple sources.',
  [DataProcessingActionType.LOADING]: 'Inserts transformed or raw data into a target system.',
  [DataProcessingActionType.MANAGEMENT]: 'Oversees the handling, storage, and usage of data.',
  [DataProcessingActionType.MASKING]: 'Hides or obscures parts of the data to protect confidentiality.',
  [DataProcessingActionType.MONITORING]: 'Observes and records data usage, access, or flow over time.',
  [DataProcessingActionType.ORGANISATION]: 'Groups data into logical structures or meaningful categories.',
  [DataProcessingActionType.POSTPROCESSING]: 'Performs additional data operations after the primary processing step.',
  [DataProcessingActionType.PREPROCESSING]: 'Prepares data for analysis or further processing.',
  [DataProcessingActionType.PROFILING]: 'Examines and analyses data to understand its structure, content and quality.',
  [DataProcessingActionType.PRODUCTION]: 'Produces data from data inputs or existing data sources.',
  [DataProcessingActionType.QUALITY_CONTROL]: 'Ensures data accuracy, completeness, and consistency.',
  [DataProcessingActionType.PROTECTION]: 'Implements measures to safeguard data from unauthorised access, alteration, or loss.',
  [DataProcessingActionType.PSEUDONYMISATION]: 'Replaces identifiers with pseudonyms while maintaining linkage capability.',
  [DataProcessingActionType.PUBLICATION]: 'Makes data available to the public or specific audiences.',
  [DataProcessingActionType.RECEPTION]: 'Accepts or ingests data from third parties or external systems.',
  [DataProcessingActionType.RECORDING]: 'Captures and stores data for the first time.',
  [DataProcessingActionType.REDACTION]: 'Removes sensitive information from data before disclosure.',
  [DataProcessingActionType.REPLICATION]: 'Copies data to other systems or locations for backup or availability.',
  [DataProcessingActionType.RESTRICTION]: 'Limits the access, use, or distribution of data.',
  [DataProcessingActionType.RESTORATION]: 'Restores data from backups or archives.',
  [DataProcessingActionType.REVIEW]: 'Checks data for correctness, completeness, and compliance.',
  [DataProcessingActionType.SHARING]: 'Provides data to other internal or authorised external parties.',
  [DataProcessingActionType.STAGING]: 'Holds data in a temporary location for processing or migration.',
  [DataProcessingActionType.STANDARDISATION]: 'Applies consistent formats or structures to data.',
  [DataProcessingActionType.STORAGE]: 'Stores data in databases, filesystems, or repositories.',
  [DataProcessingActionType.SUBMISSION]: 'Submits data to external regulatory bodies or authorities.',
  [DataProcessingActionType.STREAMING]: 'Transmits data in real-time or near-real-time.',
  [DataProcessingActionType.SUMMARISATION]: 'Produces condensed versions of data containing only key details.',
  [DataProcessingActionType.TAGGING]: 'Labels or marks data for classification or tracking.',
  [DataProcessingActionType.TRANSFER]: 'Moves data to another location, organisation, or system.',
  [DataProcessingActionType.TRANSFORMATION]: 'Changes data into a different structure, format, or representation.',
  [DataProcessingActionType.USE]: 'Utilises data for analytics, decision-making or service delivery.',
  [DataProcessingActionType.VALIDATION]: 'Checks data for correctness, completeness, and compliance.',
  [DataProcessingActionType.VERIFICATION]: 'Confirms data accuracy and consistency with its source.',
  [DataProcessingActionType.VIEWING]: 'Views data without altering it.',
};
