import { DataProcessingActionType } from './data-processing-action-type.enum';

export const DataProcessingActionTypeLabels: Record<DataProcessingActionType, string> = {
  [DataProcessingActionType.ACCESS]: 'Controls access to data or use of data.',
  [DataProcessingActionType.AGGREGATE]: 'Aggregates multiple datasets to produce summaries.',
  [DataProcessingActionType.ALTER]: 'Modifies, updates or corrects data.',
  [DataProcessingActionType.ANALYSE]: 'Analyses data for patterns, insights or profiling.',
  [DataProcessingActionType.ANONYMISE]: 'Removes identifiers irreversibly.',
  [DataProcessingActionType.ARCHIVE]: 'Archives data for long-term retention.',
  [DataProcessingActionType.AUDIT]: 'Reviews how data was processed (e.g., logs, trails).',
  [DataProcessingActionType.BACKUP]: 'Creates backups of data for disaster recovery.',
  [DataProcessingActionType.CLEANSE]: 'Removes irrelevant, outdated, incorrect or duplicate data.',
  [DataProcessingActionType.COLLECT]: 'Collects personal or sensitive data from individuals or systems.',
  [DataProcessingActionType.COMBINE]: 'Links data from multiple sources or systems.',
  [DataProcessingActionType.DECRYPT]: 'Decrypts data to make it readable again.',
  [DataProcessingActionType.DELETE]: 'Deletes data manually or programmatically.',
  [DataProcessingActionType.DESTROY]: 'Destroys data irreversibly, often for compliance.',
  [DataProcessingActionType.ENCRYPT]: 'Encrypts data using cryptographic methods.',
  [DataProcessingActionType.EXTRACT]: 'Retrieves data from one or more source systems (e.g., databases, APIs, files).',
  [DataProcessingActionType.FILTER]: 'Selects or excludes subsets of data based on defined conditions or rules.',
  [DataProcessingActionType.LOAD]: 'Inserts transformed data into a target system (e.g., database, data lake, CRM).',
  [DataProcessingActionType.MASK]: 'Masks parts of the data for confidentiality.',
  [DataProcessingActionType.MONITOR]: 'Monitors data use, access or flows in real time or over time.',
  [DataProcessingActionType.ORGANISE]: 'Organises or categorises data.',
  [DataProcessingActionType.PROFILE]: 'Builds behavioural or preference-based profiles.',
  [DataProcessingActionType.PSEUDONYMISE]: 'Pseudonymises data while maintaining linkage capability.',
  [DataProcessingActionType.RECEIVE]: 'Receives data from third parties or external systems.',
  [DataProcessingActionType.RECORD]: 'Records data for the first time in systems or logs.',
  [DataProcessingActionType.RESTRICT]: 'Restricts data access or purpose.',
  [DataProcessingActionType.RESTORE]: 'Restores data from backups.',
  [DataProcessingActionType.SHARE]: 'Shares data with other internal departments or authorised parties.',
  [DataProcessingActionType.STORE]: 'Stores data in databases, filesystems or repositories.',
  [DataProcessingActionType.TRANSFER]: 'Transfers data to another location, organisation or system.',
  [DataProcessingActionType.TRANSFORM]: 'Converts data into a usable format — includes cleansing, mapping, enriching, normalising, or reformatting.',
  [DataProcessingActionType.USE]: 'Uses data for analytics, decision-making or service delivery.'
};
