server:
  port: ${PORT:8080}
  error:
    include-message: always
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

sharedsystemshome:
  dsa:
    secret-key: ${DSA_JWT_SECRET}
    jwt:
      expiration: ${DSA_JWT_EXPIRATION_MS:60000}
    refresh:
      expiration: ${DSA_REFRESH_EXPIRATION_MS:604800000}
    timeout: ${DSA_TIMEOUT_MS:1440000}
    request:
      authentication: /api/v1/auth
      authentication.authenticate: /authenticate
      authentication.register: /register

management:
  endpoints:
    web:
      exposure:
        include: health