name: CI - Build & Test

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  frontend:
    name: Frontend - Angular Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dsa-client

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build

  backend:
    name: Backend - Spring Boot Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dsa-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Run Maven tests
        run: ./mvnw clean test
